export const projects = [
  {
    id: 1,
    title: "HKU",
    img: "https://optim.tildacdn.one/tild3864-3861-4264-a335-333831393865/-/resize/1000x/-/format/webp/__DESC.png",
    img2: "https://optim.tildacdn.one/tild6432-6566-4362-b432-343861386636/-/resize/352x/-/format/webp/__MOB.png",
    about: 'Hwasin KSTU is a company with many years of experience, high-quality projects, a team of professionals, and modern equipment that is engaged in construction, supply of goods, and outsourcing throughout Ukraine.',
    name: "Корейский университет",
    description: "Our task was to create a new website in a modern style. We implemented a solution that allows customers to edit content without creating a separate CRM system.",
    href: "",
  }, 
  {
    id: 2,
    title: "HKU",
    img: "https://optim.tildacdn.one/tild3864-3861-4264-a335-333831393865/-/resize/1000x/-/format/webp/__DESC.png",
    img2: "https://optim.tildacdn.one/tild6432-6566-4362-b432-343861386636/-/resize/352x/-/format/webp/__MOB.png",
    about: 'Hwasin KSTU is a company with many years of experience, high-quality projects, a team of professionals, and modern equipment that is engaged in construction, supply of goods, and outsourcing throughout Ukraine.',
    name: "Корейский университет",
    description: "Our task was to create a new website in a modern style. We implemented a solution that allows customers to edit content without creating a separate CRM system.",
    href: "",
  },
  {
    id: 3,
    title: "HKU",
    img: "https://optim.tildacdn.one/tild3864-3861-4264-a335-333831393865/-/resize/1000x/-/format/webp/__DESC.png",
    img2: "https://optim.tildacdn.one/tild6432-6566-4362-b432-343861386636/-/resize/352x/-/format/webp/__MOB.png",
    about: 'Hwasin KSTU is a company with many years of experience, high-quality projects, a team of professionals, and modern equipment that is engaged in construction, supply of goods, and outsourcing throughout Ukraine.',
    name: "Корейский университет",
    description: "Our task was to create a new website in a modern style. We implemented a solution that allows customers to edit content without creating a separate CRM system.",
    href: "",
  },
  {
    id: 4,
    title: "HKU",
    img: "https://optim.tildacdn.one/tild3864-3861-4264-a335-333831393865/-/resize/1000x/-/format/webp/__DESC.png",
    img2: "https://optim.tildacdn.one/tild6432-6566-4362-b432-343861386636/-/resize/352x/-/format/webp/__MOB.png",
    about: 'Hwasin KSTU is a company with many years of experience, high-quality projects, a team of professionals, and modern equipment that is engaged in construction, supply of goods, and outsourcing throughout Ukraine.',
    name: "Корейский университет",
    description: "Our task was to create a new website in a modern style. We implemented a solution that allows customers to edit content without creating a separate CRM system.",
    href: "",
  },
];
