export const projects = [
  {
    id: 1,
    title: "HKU",
    img: "https://optim.tildacdn.one/tild3864-3861-4264-a335-333831393865/-/resize/1000x/-/format/webp/__DESC.png",
    img2: "https://optim.tildacdn.one/tild6432-6566-4362-b432-343861386636/-/resize/352x/-/format/webp/__MOB.png",
    about: 'Hwasin KSTU is a company with many years of experience, high-quality projects, a team of professionals, and modern equipment that is engaged in construction, supply of goods, and outsourcing throughout Ukraine.',
    name: "Корейский университет",
    description: "Our task was to create a new website in a modern style. We implemented a solution that allows customers to edit content without creating a separate CRM system.",
    href: "",
    comingSoon: false, 
  },  
  {
    id: 2,
    title: "HKU",
    img: "https://optim.tildacdn.one/tild6430-3431-4631-b936-643331326662/-/resize/1000x/-/format/webp/sds__DESC.png",
    img2: "https://optim.tildacdn.one/tild3132-3136-4366-b537-333230316432/-/resize/352x/-/format/webp/erew__MOB.png",
    about: 'Hwasin KSTU is a company with many years of experience, high-quality projects, a team of professionals, and modern equipment that is engaged in construction, supply of goods, and outsourcing throughout Ukraine.',
    name: "Корейский университет",
    description: "Our task was to create a new website in a modern style. We implemented a solution that allows customers to edit content without creating a separate CRM system.",
    href: "",
    comingSoon: false,
  },
  {
    id: 3,
    title: "HKU",
    img: "https://optim.tildacdn.one/tild3363-3836-4432-a136-386335336335/-/resize/1000x/-/format/webp/image.png",
    img2: "https://optim.tildacdn.one/tild3135-3830-4233-b065-643930353232/-/resize/352x/-/format/webp/image.png",
    about: 'Hwasin KSTU is a company with many years of experience, high-quality projects, a team of professionals, and modern equipment that is engaged in construction, supply of goods, and outsourcing throughout Ukraine.',
    name: "Корейский университет",
    description: "Our task was to create a new website in a modern style. We implemented a solution that allows customers to edit content without creating a separate CRM system.",
    href: "",
    comingSoon: false,
  },
  {
    id: 4,
    title: "HKU",
    img: "https://optim.tildacdn.one/tild3832-3534-4234-b234-346163363962/-/resize/1000x/-/format/webp/fdg__DESC.png",
    img2: "https://optim.tildacdn.one/tild3664-6533-4336-a237-646432646431/-/resize/352x/-/format/webp/__MOB.png",
    about: 'Hwasin KSTU is a company with many years of experience, high-quality projects, a team of professionals, and modern equipment that is engaged in construction, supply of goods, and outsourcing throughout Ukraine.',
    name: "Корейский университет",
    description: "Our task was to create a new website in a modern style. We implemented a solution that allows customers to edit content without creating a separate CRM system.",
    href: "",
    comingSoon: false,
  },

  {
    id: 5,
    title: "HKU",
    img: "https://optim.tildacdn.one/tild3864-3861-4264-a335-333831393865/-/resize/1000x/-/format/webp/__DESC.png",
    img2: "https://optim.tildacdn.one/tild6432-6566-4362-b432-343861386636/-/resize/352x/-/format/webp/__MOB.png",
    about: 'Hwasin KSTU is a company with many years of experience, high-quality projects, a team of professionals, and modern equipment that is engaged in construction, supply of goods, and outsourcing throughout Ukraine.',
    name: "Корейский университет",
    description: "Our task was to create a new website in a modern style. We implemented a solution that allows customers to edit content without creating a separate CRM system.",
    href: "",
    comingSoon: false,
  }, 
  {
    id: 6,
    title: "HKU",
    img: "https://optim.tildacdn.one/tild6430-3431-4631-b936-643331326662/-/resize/1000x/-/format/webp/sds__DESC.png",
    img2: "https://optim.tildacdn.one/tild3132-3136-4366-b537-333230316432/-/resize/352x/-/format/webp/erew__MOB.png",
    about: 'Hwasin KSTU is a company with many years of experience, high-quality projects, a team of professionals, and modern equipment that is engaged in construction, supply of goods, and outsourcing throughout Ukraine.',
    name: "Корейский университет",
    description: "Our task was to create a new website in a modern style. We implemented a solution that allows customers to edit content without creating a separate CRM system.",
    href: "",
    comingSoon: false,
  },
  {
    id: 7,
    title: "HKU",
    img: "https://optim.tildacdn.one/tild3363-3836-4432-a136-386335336335/-/resize/1000x/-/format/webp/image.png",
    img2: "https://optim.tildacdn.one/tild3135-3830-4233-b065-643930353232/-/resize/352x/-/format/webp/image.png",
    about: 'Hwasin KSTU is a company with many years of experience, high-quality projects, a team of professionals, and modern equipment that is engaged in construction, supply of goods, and outsourcing throughout Ukraine.',
    name: "Корейский университет",
    description: "Our task was to create a new website in a modern style. We implemented a solution that allows customers to edit content without creating a separate CRM system.",
    href: "",
    comingSoon: false,
  },
  {
    id: 8,
    title: "HKU",
    img: "https://optim.tildacdn.one/tild3832-3534-4234-b234-346163363962/-/resize/1000x/-/format/webp/fdg__DESC.png",
    img2: "https://optim.tildacdn.one/tild3664-6533-4336-a237-646432646431/-/resize/352x/-/format/webp/__MOB.png",
    about: 'Hwasin KSTU is a company with many years of experience, high-quality projects, a team of professionals, and modern equipment that is engaged in construction, supply of goods, and outsourcing throughout Ukraine.',
    name: "Корейский университет",
    description: "Our task was to create a new website in a modern style. We implemented a solution that allows customers to edit content without creating a separate CRM system.",
    href: "",
    comingSoon: true,
  },
];
