import type { Metadata } from "next";
import "./globals.scss";
import LayoutClient from "./layout.client";
import Script from "next/script"; // Script компонентин импорттойбуз

export const metadata: Metadata = {
  title: "iant.studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LayoutClient>{children}</LayoutClient>
        <Script
          id="jivo-widget"
          src="//code.jivo.ru/widget/B3QRxgzgJO"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
